# Generated by Django 5.0 on 2024-03-12 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="room",
            new_name="room_name",
        ),
    ]
